[tools]
go = "1.26"
bun = "latest"

[env]
_.path = ["{{config_root}}/frontend/node_modules/.bin"]

[tasks]
dev = "wails3 dev"
gen-bindings = "wails3 generate bindings"
build-macos = "wails3 task darwin:package:universal"
build-all = "./build.sh"
