// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFile():Promise<any>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<any>;
