// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ReadFile shows an open file dialog and returns the data as Base64 string
 * @returns {$CancellablePromise<string[]>}
 */
export function ReadFile() {
    return $Call.ByID(88_318_641);
}

/**
 * @param {string} b64
 * @param {string} defaultPath
 * @param {string} defaultFilename
 * @returns {$CancellablePromise<string[]>}
 */
export function SaveFile(b64, defaultPath, defaultFilename) {
    return $Call.ByID(2_283_414_560, b64, defaultPath, defaultFilename);
}
